from enum import Enum

from core.base.base_enum import BaseEnum
from shared.service_layer import texts


class FileAccess(BaseEnum):
    PRIVATE = 'private'
    PUBLIC = 'public'


class FileType(BaseEnum):
    AVATAR = 'AVATAR'
    PROPERTY_DEED = 'PROPERTY_DEED'
    CHEQUE = 'CHEQUE'
    CONTRACT_PDF = 'CONTRACT_PDF'
    PROPERTY_IMAGE = 'PROPERTY_IMAGE'


class OtpType(BaseEnum):
    AUTHENTICATION = 'AUTHENTICATION'
    SIGN_CONTRACT = 'SIGN_CONTRACT'


class PropertyType(BaseEnum):
    APARTMENT_RESIDENTIAL = 'APARTMENT_RESIDENTIAL'
    APARTMENT_COMMERCIAL = 'APARTMENT_COMMERCIAL'
    APARTMENT_ADMINISTRATIVE = 'APARTMENT_ADMINISTRATIVE'
    VILLA_RESIDENTIAL = 'VILLA_RESIDENTIAL'
    VILLA_COMMERCIAL = 'VILLA_COMMERCIAL'
    LAND_RESIDENTIAL = 'LAND_RESIDENTIAL'
    LAND_COMMERCIAL = 'LAND_COMMERCIAL'
    LAND_AGRICULTURAL = 'LAND_AGRICULTURAL'
    LAND_GARDEN = "LAND_GARDEN"
    SHOP = "SHOP"
    BOOTH = 'BOOTH'
    WAREHOUS_COMMERCIAL = 'WAREHOUS_COMMERCIAL'
    HALL_COMMERCIAL = 'HALL_COMMERCIAL'
    HALL_INDUSTRIAL = 'HALL_INDUSTRIAL'
    WAREHOUSE_INDUSTRIAL = 'WAREHOUSE_INDUSTRIAL'
    SHED_COMMERCIAL = 'SHED_COMMERCIAL'
    SHED_INDUSTRIAL = 'SHED_INDUSTRIAL'
    LIVESTOCK = 'LIVESTOCK'
    DAIRY_FARM = 'DAIRY_FARM'
    POULTRY_FARM = 'POULTRY_FARM'
    INDUSTRIAL_WAREHOUSE = 'INDUSTRIAL_WAREHOUSE'
    FISH_FARM = 'FISH_FARM'
    GREENHOUSE = 'GREENHOUSE'
    FACTORY = 'FACTORY'
    WORKSHOP = 'WORKSHOP'
    SPORTS = 'SPORTS'
    HEALTHCARE = 'HEALTHCARE'
    PUBLIC_SERVICE = 'PUBLIC_SERVICE'
    PARKING = 'PARKING'
    OTHER = 'OTHER'


class PropertyFacadeType(BaseEnum):
    STONE = 'STONE'
    WOOD = 'WOOD'
    BRICK = 'BRICK'
    CLAY_AND_MD = 'CLAY_AND_MD'
    CEMENT = 'CEMENT'
    COMPOSITE = 'COMPOSITE'
    ALUMINUM = 'ALUMINUM'
    GLASS = 'GLASS'
    STONE_AND_COMPOSITE = 'STONE_AND_COMPOSITE'
    STONE_AND_CERAMICS = 'STONE_AND_CERAMICS'
    CERAMIC = 'CERAMIC'
    TRAVERTINE = 'TRAVERTINE'


class PropertyDeedStatus(BaseEnum):
    BONYAADI = 'BONYAADI'
    SHAHRDAARI = 'SHAHRDAARI'
    ASTAANE_QODS = 'ASTAANE_QODS'
    SETAADE_EJRAAYI_FARMAAN_EMAAM = 'SETAADE_EJRAAYI_FARMAAN_EMAAM'
    DOLATI = 'DOLATI'
    SHAKHSI = 'SHAKHSI'
    OQAAFI = 'OQAAFI'
    TA_AVONI = 'TA_AVONI'
    BEDOUNE_SANAD = 'BEDOUNE_SANAD'
    MOQOUFEH_AAM = 'MOQOUFEH_AAM'
    MOQOUFEH_KHAAS = 'MOQOUFEH_KHAAS'
    SHERKATE_SAHAAMIE_KHAAS = 'SHERKATE_SAHAAMIE_KHAAS'
    SHERKATE_SAHAAMIE_AAM = 'SHERKATE_SAHAMIE_AAM'


class PropertyStructureType(BaseEnum):
    RICK_OR_CINDER_LOCK = 'RICK_OR_CINDER_LOCK'
    WITHOUT_SKELETON = 'WITHOUT_SKELETON'
    CONCRETE = 'CONCRETE'
    METAL = 'METAL'
    CONCRETE_AND_METAL = 'CONCRETE_AND_METAL'
    ADOBE_OR_MUD = 'ADOBE_OR_MUD'
    WOODEN = 'WOODEN'


class PropertyFlooringType(BaseEnum):
    LIMIT = 'LIMIT'
    STONE = 'STONE'
    WOOD = 'WOOD'
    PARQUET = 'PARQUET'
    MOSAIC = 'MOSAIC'
    CERAMIC = 'CERAMIC'
    CARPET = 'CARPET'
    CEMENT = 'CEMENT'


class PropertyDirectionType(BaseEnum):
    NORTHERN = 'NORTHERN'
    SOUTHERN = 'SOUTHERN'
    WESTERN = 'WESTERN'
    EASTERN = 'EASTERN'


class PropertyRestroomType(BaseEnum):
    DOES_NOT_HAVE = 'DOES_NOT_HAVE'
    IRANI = 'IRANI'
    FARANGI = 'FARANGI'
    BOTH = 'BOTH'


class PropertyFacilitiesType(BaseEnum):
    GAS_STOVE = 'GAS_STOVE'
    JACUZZI = 'JACUZZI'
    REMOTE_CONTROLLED_DOOR = 'REMOTE_CONTROLLED_DOOR'
    ELECTRIC_SHUTTER = 'ELECTRIC_SHUTTER'
    RANGE_HOOD = 'RANGE_HOOD'
    SAUNA = 'SAUNA'
    WATER_WELL = 'WATER_WELL'
    ANTI_THEFT_DOOR = 'ANTI_THEFT_DOOR'
    SWIMMING_POOL = 'SWIMMING_POOL'
    FURNITURE = 'FURNITURE'
    BASEMENT = 'BASEMENT'
    COMMUNITY_HALL = 'COMMUNITY_HALL'
    CURTAINS = 'CURTAINS'
    LOBBY = 'LOBBY'
    GREEN_SPACE_AND_FOUNTAIN = 'GREEN_SPACE_AND_FOUNTAIN'
    CCTV = 'CCTV'
    TERRACE = 'TERRACE'
    KITCHEN_CABINETS = 'KITCHEN_CABINES'
    CARPET_FLOOR = 'CARPET_FLOOR'
    PRIVATE_YARD = 'PRIVATE_YARD'
    SPRING_ROOM = 'SPRING_ROOM'
    BALCONY = 'BALCONY'
    LIGHTING_SYSTEM = 'LIGHTING_SYSTEM'
    JANITOR_CLOSET = 'JANITOR_CLOSET'
    PATIO = 'PATIO'
    ROOF_WATER_TANK = 'ROOF_WATER_TANK'
    VIDEO_INTERCOM = 'VIDEO_INTERCOM'
    WATER_HEATER = 'WATER_HEATER'
    CHANDELIER = 'CHANDELIER'


class PropertySupplyType(BaseEnum):
    DOES_NOT_HAVE = 'DOES_NOT_HAVE'
    PUBLIC = 'PUBLIC'
    PRIVATE = 'PRIVATE'

class PropertyCoolingSystemType(BaseEnum):
    CHILLER ='CHILLER'
    WATER_COOLER = 'WATER_COOLER'
    AIR_CONDITIONER = 'AIR_CONDITIONER'
    OTHER = 'OTHER'

class PropertyHeatingSystemType(BaseEnum):
    FIREPLACE = 'FIREPLACE'
    HEATER = 'HEATER'
    TORCH = 'TORCH'
    CHILLER = 'CHILLER'
    RADIATOR = 'RADIATOR'
    PACKAGE_UNIT = 'PACKAGE_UNIT'
    OTHER = 'OTHER'

class PropertyKitchenType(BaseEnum):
    DOES_NOT_HAVE = 'DOES_NOT_HAVE'
    OPEN = 'OPEN'
    STANDARD = 'STANDARD'
    MDF = 'MDF'

class PropertyCharacteristicType(BaseEnum):
    DUPLEX = 'DUPLEX'
    PENTHOUSE = 'PENTHOUSE'
    LUXURY ='LUXURY'
    FULL_AMENITIES = 'FULL_AMENITIES'
    SEPARATE_SITTING= 'SEPARATE_SITTING'
    GARDEN_TOWER ='GARDEN_TOWER'
    LEVEL_DIFFERENCE = 'LEVEL_DIFFERENCE'
    RENOVATED  = 'RENOVATED'
    ENTIRE_FLOOR = 'ENTIRE_FLOOR'
    SEPARATE_ACCESS = 'SEPARATE_ACCESS'
    SHARED_ACCESS ='SHARED_ACCESS'
    RAW= 'RAW'

class PropertyParkingType(BaseEnum):
    COMMON= 'COMMON'
    EXCLUSIVE = 'EXCLUSIVE'
    BLOCKING = 'BLOCKING'
    COVERED = 'COVERED'
    UNCOVERED = 'UNCOVERED'
    BOX= 'BOX'

class OccupancyStatus(BaseEnum):
    NOT_OCCUPIED = 'NOT_OCCUPIED'
    OWNER_OCCUPIED = ' OWNER_OCCUPIED'
    TENANT_OCCUPIED = 'TENANT_OCCUPIED'

class SMSTemplates(Enum):
    OTP_TEMPLATE = ('OTP',texts.OTP)
    CUSTOM_PAYMENT_TEMPLATE = ('CustomPayment',texts.CustomPayment)
    SIGN_CONTRACT_OTP_TEMPLATE = ('SignContract',texts.SignContract)
    INVITATION_TO_LANDLORD_TEMPLATE = ('OwnerMustSign',texts.OwnerMustSign)
    INVITATION_TO_TENANT_TEMPLATE = ('RenterMustSign',texts.RenterMustSign)
    COUNTER_PARTY_SIGNED_TEMPLATE=('SecondSideSigned',texts.SecondSideSigned)
    COUNTER_PARTY_REJECTED_TEMPLATE=('SecondSideRejected',texts.SecondSideRejected)
    EDIT_REQUESTED_TEMPLATE = ("RevisionRequest",texts.RevisionRequest)
    WALLET_CHARGE_TEMPLATE = ('WalletCharge',texts.WalletCharge)
    INVOICE_LINK_TEMPLATE =('InvoiceLink',texts.InvoiceLink)
    PAYMENT_BEFORE_ALERT_TEMPLATE = ('PaymentBeforeAlert',texts.PaymentBeforeAlert)
    PAYMENT_AFTER_ALERT_TEMPLATE =('PaymentAfterAlert',texts.PaymentAfterAlert)
    BOTH_COMMISSIONS_PAID_TEMPLATE = ('BothCommissionsPaid',texts.BothCommissionsPaid)
    LANDLORD_COMMISSION_PAID_TEMPLATE = ('LandLordCommissionPaid',texts.LandLordCommissionPaid)
    TENANT_COMMISSION_PAID_TEMPLATE= ('TenantCommissionPaid',texts.TenantCommissionPaid)
    def __init__(self,key:str ,text:str):
        self.key = key
        self.text = text
